### ISSUE TITLE
Sample for using JDBC.NET with Dapper

### ISSUE THREAD

**Issue by kellerd** [chequer-io/JDBC.NET#24]
Curious if you would have a sample of how to use JDBC.NET with say something like Dapper.

Currently running into trouble when binding parameters using their sample.

``` 
public class Dog
        {
            public int Age { get; set; }
            public string Id { get; set; }
        }

var dog = connection.Query<Dog>("select Age = @Age, Id = @Id", new { Age = 7, Id = "Mr. Dog" });
```

Would give the error: 
The given key was not present in the dictionary.
   at JDBC.NET.Data.JdbcParameterCollection.Contains(String parameterName)
   at Dapper.DbString.AddParameter(IDbCommand command, String name) in /_/Dapper/DbString.cs:line 65
   at ParamInfo9e274bac-0a53-4256-bf31-c91b703ba22c(IDbCommand, Object)
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader) in /_/Dapper/CommandDefinition.cs:line 128
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1091
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 734

**Comment by tcables** [comment]
JDBC does not support named parameters. 

https://docs.oracle.com/javase/6/docs/api/java/sql/PreparedStatement.html

It accepts prepared statements with positional arguments.

Use:
`var dog = connection.Query<Dog>("select Age = ?, Id = ?", new { Age = 7, Id = "Mr. Dog" });`

I just tested that, and it works.
